[project]
name = "going-dutch"
version = "0.1.0"
description = "Bill splitter"
readme = "README.md"
requires-python = ">=3.14,<3.15"
dependencies = [
    "django==6.1",
    "djangorestframework==3.18.0",
    "pygments==2.21.0", # Only used for the tutorial
]

[tool.uv]
package = false
exclude-newer = "1 week"
